package com.zff.dismantle.service;

import com.zff.dismantle.api.AnalyzeResponse;
import com.zff.dismantle.api.MergedChunksResponse;
import com.zff.dismantle.chunk.Chunk;
import com.zff.dismantle.chunk.ChunkStrategy;
import com.zff.dismantle.chunk.ChunkView;
import com.zff.dismantle.chunk.FixedLengthChunker;
import com.zff.dismantle.chunk.SemanticChunker;
import com.zff.dismantle.metrics.TokenMetrics;
import com.zff.dismantle.storage.AnalysisSession;
import com.zff.dismantle.storage.ChunkStore;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Main service for Dismantle operations.
 *
 * <p>Dismantle is a utility for positioning and retrieving core information from long documents.
 * It does NOT generate responses - it only helps agents retrieve relevant chunks efficiently.</p>
 */
@Service
public class DismantleService {

    private final ChunkStore chunkStore;
    private final SemanticChunker semanticChunker;
    private final FixedLengthChunker fixedChunker;

    public DismantleService(ChunkStore chunkStore,
                            SemanticChunker semanticChunker,
                            FixedLengthChunker fixedChunker) {
        this.chunkStore = chunkStore;
        this.semanticChunker = semanticChunker;
        this.fixedChunker = fixedChunker;
    }

    /**
     * Stage A: Analyze text and split into chunks.
     * Returns session ID and chunk list (ID + title only).
     *
     * <p>Titles are generated using simple rule-based extraction.
     * For AI-generated titles, you can optionally integrate an LLM.</p>
     */
    public AnalyzeResponse analyze(String text, String strategy) {
        // Select chunking strategy
        ChunkStrategy chunkStrategy = "fixed".equals(strategy) ? fixedChunker : semanticChunker;

        // Split text into chunks
        List<Chunk> chunks = chunkStrategy.chunk(text);

        // Create session and store chunks
        String sessionId = UUID.randomUUID().toString();
        AnalysisSession session = chunkStore.createSession(sessionId, text);

        // Add chunks to session (titles already generated by chunker)
        for (Chunk chunk : chunks) {
            session.addChunk(chunk);
        }

        // Build response with minimal info (ID + title only)
        List<ChunkView> chunkViews = chunks.stream()
                .map(c -> new ChunkView(c.getId(), c.getTitle()))
                .collect(Collectors.toList());

        // Estimate original tokens (rough: 1 token ≈ 4 chars for Chinese/English mix)
        int originalTokens = text.length() / 4;

        return AnalyzeResponse.builder()
                .sessionId(sessionId)
                .chunks(chunkViews)
                .metrics(TokenMetrics.of(originalTokens, 0, 0, chunks.size()))
                .build();
    }

    /**
     * Stage B: Retrieve and merge selected chunks.
     * Returns the full content of selected chunks as merged text.
     *
     * <p>This method does NOT call any LLM. It simply retrieves and merges
     * the selected chunks. The agent then uses this merged text with their
     * own LLM (Claude, GPT-4, etc.) for inference.</p>
     *
     * <p><strong>Token Savings:</strong> By selecting only relevant chunks,
     * agents can reduce their LLM input tokens by 60-90%.</p>
     */
    public MergedChunksResponse retrieveChunks(String sessionId, List<String> chunkIds) {
        // Get session
        AnalysisSession session = chunkStore.getSession(sessionId);
        if (session == null) {
            throw new IllegalArgumentException("Session not found or expired: " + sessionId);
        }

        // Retrieve selected chunks with full content
        List<Chunk> selectedChunks = session.getChunks(chunkIds);
        if (selectedChunks.isEmpty()) {
            throw new IllegalArgumentException("No valid chunks found for given IDs");
        }

        // Merge chunks into context
        StringBuilder contextBuilder = new StringBuilder();

        for (Chunk chunk : selectedChunks) {
            contextBuilder.append("[").append(chunk.getTitle()).append("]\n");
            contextBuilder.append(chunk.getContent()).append("\n\n");
        }

        String mergedText = contextBuilder.toString().trim();

        // Build response
        List<ChunkView> selectedChunkViews = selectedChunks.stream()
                .map(c -> new ChunkView(c.getId(), c.getTitle()))
                .collect(Collectors.toList());

        // Calculate metrics
        int originalTokens = session.getOriginalText().length() / 4;
        int mergedTokens = mergedText.length() / 4;

        return MergedChunksResponse.builder()
                .mergedText(mergedText)
                .selectedChunks(selectedChunkViews)
                .metrics(TokenMetrics.of(originalTokens, mergedTokens, selectedChunks.size(), session.getChunkCount()))
                .build();
    }

    /**
     * Get session info without exposing content.
     */
    public Map<String, Object> getSessionInfo(String sessionId) {
        AnalysisSession session = chunkStore.getSession(sessionId);
        if (session == null) {
            throw new IllegalArgumentException("Session not found or expired: " + sessionId);
        }

        List<ChunkView> chunkViews = new ArrayList<>();
        for (int i = 0; i < session.getChunkCount(); i++) {
            Chunk chunk = session.getChunk("chunk_" + String.format("%03d", i));
            if (chunk != null) {
                chunkViews.add(new ChunkView(chunk.getId(), chunk.getTitle()));
            }
        }

        return Map.of(
                "sessionId", session.getSessionId(),
                "createdAt", session.getCreatedAt().toString(),
                "expiresAt", session.getExpiresAt().toString(),
                "chunkCount", session.getChunkCount(),
                "chunks", chunkViews
        );
    }

    /**
     * Delete session.
     */
    public void deleteSession(String sessionId) {
        chunkStore.deleteSession(sessionId);
    }
}
